// <auto-generated />
namespace RMS_Server_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class madeManRepack : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madeManRepack));
        
        string IMigrationMetadata.Id
        {
            get { return "201804282020375_madeManRepack"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
