// <auto-generated />
namespace RMS_Server_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderedItemsNameChangedAgainAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderedItemsNameChangedAgainAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "201801091635385_OrderedItemsNameChangedAgainAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
