// <auto-generated />
namespace RMS_Server_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inventoryModelChanged2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inventoryModelChanged2));
        
        string IMigrationMetadata.Id
        {
            get { return "201908151607441_inventoryModelChanged2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
